@startuml
'https://plantuml.com/use-case-diagram

left to right direction
package CaixaBankAplicacion {
usecase "Abrir Cuenta Corriente" as a.c.c
usecase "Cobrar Comision" as c.c
usecase "Abrir Cuenta Ahorro" as a.c.a
usecase "Ingresar Dinero" as i.d
usecase "Retirar Dinero" as r.d
usecase "Consultar Saldo" as c.s
usecase "Liquidar Cuenta" as l.c
usecase "Iniciar Sesion" as i.s
}
:Cliente: as c
:No Cliente: as n.c
:Banco: as b

n.c <|-right- c

n.c -down-> a.c.c
n.c -down-> a.c.a
c -down-> i.s
(i.d) .up.> (i.s) : extends
(r.d) .up.> (i.s) : extends
(c.s) .up.> (i.s) : extends
(l.c) .up.> (i.s) : extends
b -up-> c.c


(a.c.c) ..> (c.c) : includes
(a.c.a) ..> (c.c) : includes

@enduml